import { useEffect } from "react";
import { StyleSheet, View } from "react-native";
import Animated, {
  Easing, useAnimatedProps, useAnimatedStyle, useSharedValue, withRepeat, withTiming, interpolate
} from "react-native-reanimated";
import Svg, { Circle, Defs, RadialGradient, Stop, Rect } from "react-native-svg";

import { ink, palette } from "../theme";
import { Figure } from "./Figure";
import { Label, Text } from "./Text";

const AnimatedCircle = Animated.createAnimatedComponent(Circle);

/** The score band the program enforces: 300 floor, 850 ceiling. */
const MIN_SCORE = 300;
const MAX_SCORE = 850;

type Props = {
  score: number;
  size?: number;
};

/**
 * The credit score, as the thing the whole product turns on.
 *
 * Three tilted rings orbiting a pulsing core, with the score itself drawn as an
 * arc through the 300–850 band the program actually enforces. The rings are the
 * web hero's, rebuilt with real `rotateX`/`rotateZ` transforms rather than a CSS
 * animation — a phone has a GPU and this is what it is for.
 *
 * Every ring turns at a different rate and on a different axis. Matched speeds
 * read as one rigid object spinning, which is flat; mismatched ones read as
 * depth, which is the point.
 *
 * All of it runs on the UI thread through Reanimated, so the orb keeps turning
 * while the JS thread is busy fetching a credit line — which is exactly when
 * this screen is on show.
 */
export function CreditOrb({ score, size = 260 }: Props) {
  const spin = useSharedValue(0);
  const counter = useSharedValue(0);
  const pulse = useSharedValue(0);
  const arc = useSharedValue(0);

  const r = size * 0.36;
  const circumference = 2 * Math.PI * r;
  const pct = Math.max(0, Math.min(1, (score - MIN_SCORE) / (MAX_SCORE - MIN_SCORE)));

  useEffect(() => {
    spin.value = withRepeat(
      withTiming(1, { duration: 30_000, easing: Easing.linear }),
      -1,
      false,
    );
    counter.value = withRepeat(
      withTiming(1, { duration: 46_000, easing: Easing.linear }),
      -1,
      false,
    );
    // Breathing, not blinking: a long ease in both directions.
    pulse.value = withRepeat(
      withTiming(1, { duration: 4_000, easing: Easing.inOut(Easing.quad) }),
      -1,
      true,
    );
  }, []);

  useEffect(() => {
    arc.value = withTiming(pct, {
      duration: 1_200,
      easing: Easing.bezier(0.16, 1, 0.3, 1),
    });
  }, [pct]);

  // Written out rather than generated by a helper. A loop or a closure that
  // calls useAnimatedStyle is a hook called outside a component body — it
  // happens to work while the call order is fixed, and breaks silently the
  // moment someone makes the ring count conditional.
  const ring1 = useAnimatedStyle(() => ({
    transform: [
      { perspective: 900 },
      { rotateX: "74deg" },
      { rotateZ: `${spin.value * 360}deg` },
    ],
  }));
  const ring2 = useAnimatedStyle(() => ({
    transform: [
      { perspective: 900 },
      { rotateX: "46deg" },
      { rotateZ: `${45 + counter.value * 1.6 * 360}deg` },
    ],
  }));
  const ring3 = useAnimatedStyle(() => ({
    transform: [
      { perspective: 900 },
      { rotateX: "-48deg" },
      { rotateZ: `${60 + spin.value * 0.7 * 360}deg` },
    ],
  }));
  const ring4 = useAnimatedStyle(() => ({
    transform: [
      { perspective: 900 },
      { rotateX: "88deg" },
      { rotateZ: `${15 + counter.value * 0.45 * 360}deg` },
    ],
  }));

  const core = useAnimatedStyle(() => ({
    transform: [{ scale: interpolate(pulse.value, [0, 1], [1, 1.35]) }],
    opacity: interpolate(pulse.value, [0, 1], [0.45, 0.9]),
  }));

  const arcProps = useAnimatedProps(() => ({
    strokeDashoffset: circumference * (1 - arc.value),
  }));

  const ellipse = (w: number, h: number, opacity: number, dashed = false) => ({
    position: "absolute" as const,
    width: w,
    height: h,
    marginLeft: -w / 2,
    marginTop: -h / 2,
    left: "50%" as const,
    top: "50%" as const,
    borderRadius: Math.max(w, h) / 2,
    borderWidth: dashed ? 1 : 1.5,
    borderStyle: dashed ? ("dashed" as const) : ("solid" as const),
    borderColor: palette.glow,
    opacity,
  });

  return (
    <View style={[styles.wrap, { width: size, height: size }]}>
      {/* The bloom behind everything. */}
      <Animated.View style={[styles.coreGlow, { width: size, height: size }, core]}>
        <Svg width={size} height={size}>
          <Defs>
            <RadialGradient id="core" cx="0.5" cy="0.5" r="0.5">
              <Stop offset="0" stopColor={palette.glow} stopOpacity="0.55" />
              <Stop offset="0.45" stopColor={palette.glow} stopOpacity="0.14" />
              <Stop offset="1" stopColor={palette.glow} stopOpacity="0" />
            </RadialGradient>
          </Defs>
          <Rect width={size} height={size} fill="url(#core)" />
        </Svg>
      </Animated.View>

      <Animated.View style={[ellipse(size * 0.98, size * 0.98, 0.16, true), ring4]} />
      <Animated.View style={[ellipse(size * 0.88, size * 0.88, 0.5), ring1]} />
      <Animated.View style={[ellipse(size * 0.74, size * 0.74, 0.34), ring2]} />
      <Animated.View style={[ellipse(size * 0.62, size * 0.62, 0.24), ring3]} />

      {/* The score arc: a real measurement, drawn through the enforced band. */}
      <Svg width={size} height={size} style={StyleSheet.absoluteFill}>
        <Circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          stroke={ink.hairline}
          strokeWidth={3}
          fill="none"
        />
        <AnimatedCircle
          cx={size / 2}
          cy={size / 2}
          r={r}
          stroke={palette.primary}
          strokeWidth={3}
          strokeLinecap="round"
          fill="none"
          strokeDasharray={`${circumference} ${circumference}`}
          animatedProps={arcProps}
          // Start the arc at twelve o'clock rather than three.
          transform={`rotate(-90 ${size / 2} ${size / 2})`}
        />
      </Svg>

      <View style={styles.center}>
        <Label>Credit score</Label>
        <Figure
          value={score * 1_000_000}
          decimals={0}
          variant="hero"
          tone="lime"
          group={false}
          style={{ marginTop: 8 }}
        />
        <Text variant="bodySmall" tone="faint" style={{ marginTop: 8 }}>
          {MIN_SCORE} – {MAX_SCORE}
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  coreGlow: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  center: {
    alignItems: "center",
    justifyContent: "center",
  },
});
